### PR TITLE
Add update notifier to app and addon generators

### PR DESCRIPTION
**Pull request by tiberiuichim**
Using [update-notifier](https://github.com/yeoman/update-notifier)

### CODE REVIEW

**Comment by tiberiuichim** [comment]
I've also added a semi-ok eslintrc (it doesn't do autoformatting) and upgraded release-it, npm was complaining about a minor security issue.

**Comment by tiberiuichim** [comment]
Screenshot 2020-12-01 224315

And this is how it looks like in action.

**Comment by tiberiuichim** [comment]
I've changed the text to "It's important to have the generators updated!"

**Review by sneridagh — APPROVED** [review]

**Review by avoinea — APPROVED** [review]

**Comment by avoinea** [comment]
@tiberiuichim Shouldn't it be?
```
Run "npm install -g @plone/generator-volto" to update
```

**Comment by tiberiuichim** [comment]
@avoinea good catch. I think it's due to the fact that we have a yarn.lock, I'll delete the file and generate a package.lock.

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
