### PR TITLE
Add interactive and workspace options

### PR DESCRIPTION
**Pull request by avoinea**
Add:
* `--interactive` / `--no-interactive`
* `--workspace`
* `--skip-workspaces`

### CODE REVIEW

**Review by tiberiuichim — APPROVED** [review]

**Review by sneridagh — APPROVED** [review]
Nice! I worked on it a bit this weekend too :) . My version is able to infer the path for the workspace (given the fact of having some sensible defaults in place, of course). Can we pass the workspace path via command line too?

@avoinea @tiberiuichim what do you think? Also we could populate the mrs.developer.json file automatically too. Also, if no workspace path is given, apply the sensible defaults.

**Comment by tiberiuichim** [comment]
@sneridagh maybe my brain is twisted by previous experience, but it makes sense to have something like mr.developer (because we already have mrs-developer) where you can say: I want these addons to be "activated for development", which would automatically add them to workspace and to "addons" in package.json. It would also be cool if we could `missdev add some_github_link` and so on.

**Comment by avoinea** [comment]
> Can we pass the workspace path via command line too?

Yes, 

```bash
$ cd my-volto-project
$ yo @plone/volto --addon=volto-slate:asDefault --addon=volto-form-builder --workspace src/addons/volto-slate --workspace src/addons/volto-form-builder --no-interactive
```
 
> @avoinea @tiberiuichim what do you think? Also we could populate the mrs.developer.json file automatically too. Also, if no workspace path is given, apply the sensible defaults.

I was also thinking about `mrs.developer.json`, but this is another story as it required more settings, like github url, package name, branch, path, e.g.:

```
     "volto-slate-metadata-mentions": {
         "url": "https://github.com/eea/volto-slate-metadata-mentions.git",
         "package": "@eeacms/volto-slate-metadata-mentions",
         "branch": "master",
         "path": "src"
     },
```

**Comment by tiberiuichim** [comment]
But can we say: you can pass to yo generator (or just automatically read, if it exists) any mrs.developer.json, then activate and install all those addons, by default?

**Comment by sneridagh** [comment]
> @sneridagh maybe my brain is twisted by previous experience, but it makes sense to have something like mr.developer (because we already have mrs-developer) where you can say: I want these addons to be "activated for development", which would automatically add them to workspace and to "addons" in package.json. It would also be cool if we could `missdev add some_github_link` and so on.

in fact we can :) we only need to convince @ebrehault about it!

**Pull request merged**
